version: '3.4'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--configFile=./traefik.yml"
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml"
      - "./letsencrypt/acme.json:/acme.json"
    networks:
      - traefik_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "root" 
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql # Chemin du script d'initialisation
    networks:
      - db_network
    ports:
      - "3306:3306"
    restart: always

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    depends_on:
      - mariadb
      - traefik
    environment:
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: alpha_db
      MYSQL_USER: alpha
      MYSQL_PASSWORD: "alpha_password"
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - db_network
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme='https'"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent='true'"
      - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.entrypoints=insecure"
      - "traefik.http.routers.nextcloud.middlewares='https-redirect@docker'"
      - "traefik.http.routers.nextcloud_https.entrypoints=secure"
      - "traefik.http.routers.nextcloud_https.tls=true"
      - "traefik.http.routers.nextcloud_https.rule=Host(`cloud.sihamk.uca-devops.ovh`)"
      - "traefik.http.routers.nextcloud_https.tls.certresolver=letsencrypt"
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mariadb
      - traefik
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: beta
      WORDPRESS_DB_PASSWORD: "beta_password"  
      WORDPRESS_DB_NAME: beta_db
    ports:
      - "8081:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - db_network
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme='https'"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent='true'"
      - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress.entrypoints=insecure"
      - "traefik.http.routers.wordpress.middlewares='https-redirect@docker'"
      - "traefik.http.routers.wordpress_https.entrypoints=secure"
      - "traefik.http.routers.wordpress_https.tls=true"
      - "traefik.http.routers.wordpress_https.rule=Host(`blog.sihamk.uca-devops.ovh`)"
      - "traefik.http.routers.wordpress_https.tls.certresolver=letsencrypt"
    restart: always

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        GIT_REPO: https://git.forestier.re/uca/2022-2023/devops-m1/tp-not/code-tp-note
    ports:
      - "8000:80"
    networks:
      - isolated_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme='https'"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent='true'"
      - "traefik.http.services.docker_app_1-service.loadbalancer.server.port=80"
      - "traefik.http.routers.docker_app_1.entrypoints=insecure"
      - "traefik.http.routers.docker_app_1.middlewares='https-redirect@docker'"
      - "traefik.http.routers.docker_app_1_https.entrypoints=secure"
      - "traefik.http.routers.docker_app_1_https.tls=true"
      - "traefik.http.routers.docker_app_1_https.rule=Host(`projet.sihamk.uca-devops.ovh`)"
      - "traefik.http.routers.docker_app_1_https.tls.certresolver=letsencrypt"
    restart: always



  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command: "--path.rootfs=/host"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    environment:
      STORAGE_TSDB_PATH: "/prometheus"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SERVER_ROOT_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    restart: always

networks:
  db_network:
  isolated_network:
  traefik_network:

volumes:
  mariadb_data:
  nextcloud_data:
  wordpress_data:
  prometheus_data:

